development:
  sessions:
    default:
      database: monitoramento-prefeitura
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: monitoramento-prefeitura
      hosts:
        - localhost:27017